services:
  - type: web
    name: verivotex-backend
    env: node
    buildCommand: "cd Backend && npm install"
    startCommand: "cd Backend && node server.js"
    envVars:
      - key: PORT
        value: 3000
